/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.User;
import model.UserList;

/**
 *
 * @author sanatpopli
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    
    

    

    
    User user;
    public LoginJPanel(User user) {
        initComponents();
        this.user=user;
         // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingJLabel = new javax.swing.JLabel();
        txtNeuid = new javax.swing.JTextField();
        txtUserid = new javax.swing.JTextField();
        neuidjLabel = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        useridjLabel = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        usernamejLabel = new javax.swing.JLabel();
        passwordjLabel = new javax.swing.JLabel();
        loginuserjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));

        headingJLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        headingJLabel.setText("Login Pal!");

        neuidjLabel.setText("NEUID");

        useridjLabel.setText("User ID");

        usernamejLabel.setText("Name");

        passwordjLabel.setText("Password");

        loginuserjButton.setText("Hit!");
        loginuserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginuserjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(useridjLabel)
                            .addComponent(neuidjLabel)
                            .addComponent(usernamejLabel)
                            .addComponent(passwordjLabel))
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUserName)
                                .addComponent(txtNeuid)
                                .addComponent(txtUserid, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginuserjButton)
                            .addComponent(headingJLabel))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(headingJLabel)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(neuidjLabel)
                        .addGap(33, 33, 33)
                        .addComponent(useridjLabel)
                        .addGap(38, 38, 38)
                        .addComponent(usernamejLabel)
                        .addGap(28, 28, 28)
                        .addComponent(passwordjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNeuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txtUserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(loginuserjButton)
                .addGap(197, 197, 197))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginuserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginuserjButtonActionPerformed
        // TODO add your handling code here:
         user.setNeuid(txtNeuid.getText());
         user.setUserid(txtUserid.getText());
         user.setUsername(txtUserName.getText());
         user.setPassword(txtPassword.getText());
        
        JOptionPane.showMessageDialog(this, "Product Information Saved");
    }//GEN-LAST:event_loginuserjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headingJLabel;
    private javax.swing.JButton loginuserjButton;
    private javax.swing.JLabel neuidjLabel;
    private javax.swing.JLabel passwordjLabel;
    private javax.swing.JTextField txtNeuid;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserid;
    private javax.swing.JLabel useridjLabel;
    private javax.swing.JLabel usernamejLabel;
    // End of variables declaration//GEN-END:variables
}
