/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import javax.swing.JOptionPane;
import model.Hospital;

/**
 *
 * @author sanatpopli
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    Hospital hospital;
    public DoctorJPanel(Hospital hospital) {
        
        
        initComponents();
        this.hospital=hospital;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        DOCdetailjLabel = new javax.swing.JLabel();
        DrjLabel = new javax.swing.JLabel();
        QualjLabel = new javax.swing.JLabel();
        SpecialityjLabel = new javax.swing.JLabel();
        txtDr = new javax.swing.JTextField();
        txtQual = new javax.swing.JTextField();
        txtSpeciality = new javax.swing.JTextField();
        ExpjLabel = new javax.swing.JLabel();
        FeejLabel = new javax.swing.JLabel();
        VisitjLabel = new javax.swing.JLabel();
        DatejLabel = new javax.swing.JLabel();
        txtExperience = new javax.swing.JTextField();
        txtFee = new javax.swing.JTextField();
        txtVisit = new javax.swing.JTextField();
        txtNextd = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        DOCdetailjLabel.setText("Doctor Detail");

        DrjLabel.setText("Name");

        QualjLabel.setText("Qualification");

        SpecialityjLabel.setText("Specialisation");

        txtQual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQualActionPerformed(evt);
            }
        });

        ExpjLabel.setText("Experience");

        FeejLabel.setText("FEE");

        VisitjLabel.setText("Visit Time");

        DatejLabel.setText("Next date");

        txtFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeeActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DatejLabel)
                    .addComponent(VisitjLabel)
                    .addComponent(ExpjLabel)
                    .addComponent(QualjLabel)
                    .addComponent(DrjLabel)
                    .addComponent(SpecialityjLabel)
                    .addComponent(FeejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(txtQual, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSpeciality, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFee, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtExperience, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtVisit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNextd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(DOCdetailjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btnSave)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(DOCdetailjLabel)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DrjLabel)
                            .addComponent(txtDr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QualjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SpecialityjLabel)
                            .addComponent(txtSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ExpjLabel)
                            .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FeejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VisitjLabel)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatejLabel)
                    .addComponent(txtNextd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtQualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQualActionPerformed

    private void txtFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        hospital.setName(txtDr.getText());
        hospital.setQualification(txtQual.getText());
        hospital.setSpecialisation(txtSpeciality.getText());
        hospital.setExperience(txtExperience.getText());
        hospital.setFee(txtFee.getText());
        hospital.setVisit(txtVisit.getText());
        hospital.setNextDate(txtNextd.getText());
        
        JOptionPane.showMessageDialog(this, "Information Saved");
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOCdetailjLabel;
    private javax.swing.JLabel DatejLabel;
    private javax.swing.JLabel DrjLabel;
    private javax.swing.JLabel ExpjLabel;
    private javax.swing.JLabel FeejLabel;
    private javax.swing.JLabel QualjLabel;
    private javax.swing.JLabel SpecialityjLabel;
    private javax.swing.JLabel VisitjLabel;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtDr;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtFee;
    private javax.swing.JTextField txtNextd;
    private javax.swing.JTextField txtQual;
    private javax.swing.JTextField txtSpeciality;
    private javax.swing.JTextField txtVisit;
    // End of variables declaration//GEN-END:variables
}
