/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Student;

/**
 *
 * @author sanatpopli
 */
public class SignupJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignupJPanel
     */
    public SignupJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingjLabel = new javax.swing.JLabel();
        firstjLabel = new javax.swing.JLabel();
        lastjLabel = new javax.swing.JLabel();
        emailjLabel = new javax.swing.JLabel();
        agejLabel = new javax.swing.JLabel();
        UserNamejLabel = new javax.swing.JLabel();
        PasswordjLabel = new javax.swing.JLabel();
        NUIDjLabel = new javax.swing.JLabel();
        DegreejLabel = new javax.swing.JLabel();
        MajorjLabel = new javax.swing.JLabel();
        MinorjLabel = new javax.swing.JLabel();
        btnSign = new javax.swing.JButton();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtNUID = new javax.swing.JTextField();
        txtDegree = new javax.swing.JTextField();
        txtMajor = new javax.swing.JTextField();
        txtMinor = new javax.swing.JTextField();
        backButto = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 255));

        headingjLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        headingjLabel.setText("Signup!");

        firstjLabel.setText("FirstName");

        lastjLabel.setText("LastName");

        emailjLabel.setText("Email");

        agejLabel.setText("Age");

        UserNamejLabel.setText("UserName");

        PasswordjLabel.setText("Password");

        NUIDjLabel.setText("NUID");

        DegreejLabel.setText("Degree");

        MajorjLabel.setText("Major");

        MinorjLabel.setText("Minor");

        btnSign.setText("Signup");
        btnSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignActionPerformed(evt);
            }
        });

        backButto.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(btnSign)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lastjLabel)
                        .addComponent(firstjLabel))
                    .addComponent(agejLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserNamejLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PasswordjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NUIDjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DegreejLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MajorjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MinorjLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNUID, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDegree, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMajor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMinor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName)
                    .addComponent(txtEmail))
                .addGap(219, 219, 219))
            .addGroup(layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(headingjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButto)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headingjLabel)
                    .addComponent(backButto))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstjLabel)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastjLabel)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailjLabel)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agejLabel)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNamejLabel)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordjLabel)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUIDjLabel)
                    .addComponent(txtNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DegreejLabel)
                    .addComponent(txtDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MajorjLabel)
                    .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MinorjLabel)
                    .addComponent(txtMinor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSign)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DegreejLabel;
    private javax.swing.JLabel MajorjLabel;
    private javax.swing.JLabel MinorjLabel;
    private javax.swing.JLabel NUIDjLabel;
    private javax.swing.JLabel PasswordjLabel;
    private javax.swing.JLabel UserNamejLabel;
    private javax.swing.JLabel agejLabel;
    private javax.swing.JButton backButto;
    private javax.swing.JButton btnSign;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JLabel firstjLabel;
    private javax.swing.JLabel headingjLabel;
    private javax.swing.JLabel lastjLabel;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDegree;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMajor;
    private javax.swing.JTextField txtMinor;
    private javax.swing.JTextField txtNUID;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
